title: Reynaldi's Blog
description: >-
  Blog of Reynaldi Chernando

author:
  name: Reynaldi Chernando
  email: "reynaldichernando@gmail.com"

minima:
  social_links:
    - title: Reynaldi's Twitter
      icon: x-twitter
      url: "https://x.com/reynaldicher"
    - title: Reynaldi's GitHub
      icon: github
      url: "https://github.com/reynaldichernando"
    - title: Reynaldi's LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/reynaldichernando"
    - title: Corsfix CORS Proxy
      icon: globe
      fa_namespace: solid
      url: "https://corsfix.com"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
